% Generate and plot an AM-FM sinusoid for decreasing sampling intervals
% Generates an AM-FM sinusoid
% s(t) = A*cos(2*pi*f1*t)*sin(2*pi*f0*t + b*cos(2*pi*f1*t)) and plots it
% for several sampling intervals, from coarse to fine. Reduce the sampling
% interval until the plot stops changing significantly.
% The signal is generated by the local function GENAMFMSIG at the end of
% this file. It then plots the periodogram of the most finely sampled signal.

% Daniel Rodriguez, September 2026

%% Signal parameters
snr = 10;               % Matched filtering SNR (sets the amplitude A)
modIndex = 3;           % Modulation index b (strength of frequency swing)
carrierFreq = 10;       % Carrier frequency f0 in Hz
modFreq = 2;            % Modulation frequency f1 in Hz (used for AM and FM)
amfmParams = [modIndex, carrierFreq, modFreq];
sigDuration = 1;        % Length of the signal in seconds

%% Maximum frequency
% The FM part swings the frequency up to f0 + b*f1, and the AM part
% (multiplying by cos(2*pi*f1*t)) shifts frequencies by up to f1 more
maxFreq = carrierFreq + modIndex*modFreq + modFreq;
disp(['Maximum frequency = ', num2str(maxFreq), ' Hz']);

%% Sampling frequencies to try, as multiples of maxFreq
sampFreqList = [2, 5, 10, 50]*maxFreq;
nPlots = length(sampFreqList);

%% Generate and plot the signal for each sampling frequency
figure;
for k = 1:nPlots
    sampFreq = sampFreqList(k);                 % 1/Delta
    sampIntrvl = 1/sampFreq;                    % Delta
    nSamples = floor(sigDuration/sampIntrvl);   % N
    timeVec = (0:(nSamples-1))*sampIntrvl;      % t = n*Delta, n = 0,...,N-1

    sigVec = genamfmsig(timeVec, snr, amfmParams);

    subplot(nPlots, 1, k);
    plot(timeVec, sigVec, '.-');
    xlabel('Time (sec)');
    ylabel('AM-FM sinusoid');
    title(['Sampling frequency = ', num2str(sampFreq), ' Hz (', ...
           num2str(sampFreq/maxFreq), ' x max. frequency)']);
end

%% Periodogram (magnitude of the FFT)
% Uses the signal from the last (finest) sampling frequency in the loop
kNyq = floor(nSamples/2) + 1;           % Index of the Nyquist frequency
freqSpacing = 1/(nSamples*sampIntrvl);  % Frequency spacing 1/(N*Delta)
posFreq = (0:(kNyq-1))*freqSpacing;     % Positive Fourier frequencies
fftSig = fft(sigVec);
fftSig = fftSig(1:kNyq);                % Keep positive frequencies only

figure;
plot(posFreq, abs(fftSig), '.-');
xlim([0, 2*maxFreq]);                   % Zoom in on where the signal is
xlabel('Frequency (Hz)');
ylabel('|FFT|');
title('Periodogram: AM-FM sinusoid');

%% Local function
function sigVec = genamfmsig(dataX,snr,amfmParams)
% Generate an AM-FM sinusoid
% S = GENAMFMSIG(X,SNR,P)
% Generates an AM-FM sinusoid S. X is the vector of time stamps at which
% the samples of the signal are to be computed. SNR is the matched
% filtering signal-to-noise ratio of S and P is the vector of three
% parameters [b, f0, f1] of the signal:
% cos(2*pi*f1*t)*sin(2*pi*f0*t + b*cos(2*pi*f1*t)), where b is the
% modulation index, f0 is the carrier frequency in Hz and f1 is the
% modulation frequency in Hz.

modVec = cos(2*pi*amfmParams(3)*dataX);
phaseVec = 2*pi*amfmParams(2)*dataX + amfmParams(1)*modVec;
sigVec = modVec.*sin(phaseVec);
sigVec = snr*sigVec/norm(sigVec);
end
