% Generate and plot an AM sinusoid for decreasing sampling intervals
% Generates an amplitude modulated (AM) sinusoid
% s(t) = A*cos(2*pi*f1*t)*sin(2*pi*f0*t + phi0) and plots it for several
% sampling intervals, from coarse to fine. Reduce the sampling interval
% until the plot stops changing significantly.
% The signal is generated by the local function GENAMSIG at the end of
% this file. It then plots the periodogram of the most finely sampled signal.

% Daniel Rodriguez, September 2026

%% Signal parameters
snr = 10;               % Matched filtering SNR (sets the amplitude A)
carrierFreq = 10;       % Carrier frequency f0 in Hz
modFreq = 1;            % Modulation frequency f1 in Hz
initPhase = 0;          % Initial phase phi0 in radians
amParams = [carrierFreq, modFreq, initPhase];
sigDuration = 1;        % Length of the signal in seconds

%% Maximum frequency
% cos(2*pi*f1*t)*sin(2*pi*f0*t) is the sum of two sinusoids with
% frequencies f0 - f1 and f0 + f1, so the highest frequency is f0 + f1
maxFreq = carrierFreq + modFreq;
disp(['Maximum frequency = ', num2str(maxFreq), ' Hz']);

%% Sampling frequencies to try, as multiples of maxFreq
sampFreqList = [2, 5, 10, 50]*maxFreq;
nPlots = length(sampFreqList);

%% Generate and plot the signal for each sampling frequency
figure;
for k = 1:nPlots
    sampFreq = sampFreqList(k);                 % 1/Delta
    sampIntrvl = 1/sampFreq;                    % Delta
    nSamples = floor(sigDuration/sampIntrvl);   % N
    timeVec = (0:(nSamples-1))*sampIntrvl;      % t = n*Delta, n = 0,...,N-1

    sigVec = genamsig(timeVec, snr, amParams);

    subplot(nPlots, 1, k);
    plot(timeVec, sigVec, '.-');
    xlabel('Time (sec)');
    ylabel('AM sinusoid');
    title(['Sampling frequency = ', num2str(sampFreq), ' Hz (', ...
           num2str(sampFreq/maxFreq), ' x max. frequency)']);
end

%% Periodogram (magnitude of the FFT)
% Uses the signal from the last (finest) sampling frequency in the loop
kNyq = floor(nSamples/2) + 1;           % Index of the Nyquist frequency
freqSpacing = 1/(nSamples*sampIntrvl);  % Frequency spacing 1/(N*Delta)
posFreq = (0:(kNyq-1))*freqSpacing;     % Positive Fourier frequencies
fftSig = fft(sigVec);
fftSig = fftSig(1:kNyq);                % Keep positive frequencies only

figure;
plot(posFreq, abs(fftSig), '.-');
xlim([0, 2*maxFreq]);                   % Zoom in on where the signal is
xlabel('Frequency (Hz)');
ylabel('|FFT|');
title('Periodogram: AM sinusoid');

%% Local function
function sigVec = genamsig(dataX,snr,amParams)
% Generate an amplitude modulated (AM) sinusoid
% S = GENAMSIG(X,SNR,P)
% Generates an AM sinusoid S. X is the vector of time stamps at which the
% samples of the signal are to be computed. SNR is the matched filtering
% signal-to-noise ratio of S and P is the vector of three parameters
% [f0, f1, phi0] of the signal: cos(2*pi*f1*t)*sin(2*pi*f0*t + phi0),
% where f0 is the carrier frequency in Hz, f1 is the modulation frequency
% in Hz and phi0 is the initial phase in radians.

envVec = cos(2*pi*amParams(2)*dataX);
sigVec = envVec.*sin(2*pi*amParams(1)*dataX + amParams(3));
sigVec = snr*sigVec/norm(sigVec);
end
