% Generate and plot an FM sinusoid for decreasing sampling intervals
% Generates a frequency modulated (FM) sinusoid
% s(t) = A*sin(2*pi*f0*t + b*cos(2*pi*f1*t)) and plots it for several
% sampling intervals, from coarse to fine. Reduce the sampling interval
% until the plot stops changing significantly.
% The signal is generated by the local function GENFMSIG at the end of
% this file. It then plots the periodogram of the most finely sampled signal.

% Daniel Rodriguez, September 2026

%% Signal parameters
snr = 10;               % Matched filtering SNR (sets the amplitude A)
modIndex = 3;           % Modulation index b (strength of frequency swing)
carrierFreq = 10;       % Carrier frequency f0 in Hz
modFreq = 2;            % Modulation frequency f1 in Hz
fmParams = [modIndex, carrierFreq, modFreq];
sigDuration = 1;        % Length of the signal in seconds

%% Maximum instantaneous frequency
% f(t) = (1/(2*pi))*d(phase)/dt = f0 - b*f1*sin(2*pi*f1*t),
% which swings between f0 - b*f1 and f0 + b*f1
maxFreq = carrierFreq + modIndex*modFreq;
disp(['Maximum instantaneous frequency = ', num2str(maxFreq), ' Hz']);

%% Sampling frequencies to try, as multiples of maxFreq
sampFreqList = [2, 5, 10, 50]*maxFreq;
nPlots = length(sampFreqList);

%% Generate and plot the signal for each sampling frequency
figure;
for k = 1:nPlots
    sampFreq = sampFreqList(k);                 % 1/Delta
    sampIntrvl = 1/sampFreq;                    % Delta
    nSamples = floor(sigDuration/sampIntrvl);   % N
    timeVec = (0:(nSamples-1))*sampIntrvl;      % t = n*Delta, n = 0,...,N-1

    sigVec = genfmsig(timeVec, snr, fmParams);

    subplot(nPlots, 1, k);
    plot(timeVec, sigVec, '.-');
    xlabel('Time (sec)');
    ylabel('FM sinusoid');
    title(['Sampling frequency = ', num2str(sampFreq), ' Hz (', ...
           num2str(sampFreq/maxFreq), ' x max. frequency)']);
end

%% Periodogram (magnitude of the FFT)
% Uses the signal from the last (finest) sampling frequency in the loop
kNyq = floor(nSamples/2) + 1;           % Index of the Nyquist frequency
freqSpacing = 1/(nSamples*sampIntrvl);  % Frequency spacing 1/(N*Delta)
posFreq = (0:(kNyq-1))*freqSpacing;     % Positive Fourier frequencies
fftSig = fft(sigVec);
fftSig = fftSig(1:kNyq);                % Keep positive frequencies only

figure;
plot(posFreq, abs(fftSig), '.-');
xlim([0, 2*maxFreq]);                   % Zoom in on where the signal is
xlabel('Frequency (Hz)');
ylabel('|FFT|');
title('Periodogram: FM sinusoid');

%% Local function
function sigVec = genfmsig(dataX,snr,fmParams)
% Generate a frequency modulated (FM) sinusoid
% S = GENFMSIG(X,SNR,P)
% Generates an FM sinusoid S. X is the vector of time stamps at which the
% samples of the signal are to be computed. SNR is the matched filtering
% signal-to-noise ratio of S and P is the vector of three parameters
% [b, f0, f1] of the signal: sin(2*pi*f0*t + b*cos(2*pi*f1*t)), where b is
% the modulation index, f0 is the carrier frequency in Hz and f1 is the
% modulation frequency in Hz.

phaseVec = 2*pi*fmParams(2)*dataX + fmParams(1)*cos(2*pi*fmParams(3)*dataX);
sigVec = sin(phaseVec);
sigVec = snr*sigVec/norm(sigVec);
end
