% Generate and plot a linear chirp signal for decreasing sampling intervals
% Generates a linear chirp signal
% s(t) = A*sin(2*pi*(f0*t + 0.5*f1*t^2) + phi0) and plots it for several
% sampling intervals, from coarse to fine. Reduce the sampling interval
% until the plot stops changing significantly.
% The signal is generated by the local function GENLCSIG at the end of
% this file. It then plots the periodogram of the most finely sampled signal.

% Daniel Rodriguez, September 2026

%% Signal parameters
snr = 10;               % Matched filtering SNR (sets the amplitude A)
startFreq = 5;          % Frequency f0 at t = 0, in Hz
freqRate = 20;          % Rate of increase of frequency f1, in Hz per second
initPhase = 0;          % Initial phase phi0 in radians
lcParams = [startFreq, freqRate, initPhase];
sigDuration = 1;        % Length of the signal in seconds

%% Maximum instantaneous frequency
% f(t) = f0 + f1*t is largest at the end of the signal (for f1 > 0)
maxFreq = startFreq + freqRate*sigDuration;
disp(['Maximum instantaneous frequency = ', num2str(maxFreq), ' Hz']);

%% Sampling frequencies to try, as multiples of maxFreq
sampFreqList = [2, 5, 10, 50]*maxFreq;
nPlots = length(sampFreqList);

%% Generate and plot the signal for each sampling frequency
figure;
for k = 1:nPlots
    sampFreq = sampFreqList(k);                 % 1/Delta
    sampIntrvl = 1/sampFreq;                    % Delta
    nSamples = floor(sigDuration/sampIntrvl);   % N
    timeVec = (0:(nSamples-1))*sampIntrvl;      % t = n*Delta, n = 0,...,N-1

    sigVec = genlcsig(timeVec, snr, lcParams);

    subplot(nPlots, 1, k);
    plot(timeVec, sigVec, '.-');
    xlabel('Time (sec)');
    ylabel('Lin. Chirp');
    title(['Sampling frequency = ', num2str(sampFreq), ' Hz (', ...
           num2str(sampFreq/maxFreq), ' x max. frequency)']);
end

%% Periodogram (magnitude of the FFT)
% Uses the signal from the last (finest) sampling frequency in the loop
kNyq = floor(nSamples/2) + 1;           % Index of the Nyquist frequency
freqSpacing = 1/(nSamples*sampIntrvl);  % Frequency spacing 1/(N*Delta)
posFreq = (0:(kNyq-1))*freqSpacing;     % Positive Fourier frequencies
fftSig = fft(sigVec);
fftSig = fftSig(1:kNyq);                % Keep positive frequencies only

figure;
plot(posFreq, abs(fftSig), '.-');
xlim([0, 2*maxFreq]);                   % Zoom in on where the signal is
xlabel('Frequency (Hz)');
ylabel('|FFT|');
title('Periodogram: linear chirp');

%% Local function
function sigVec = genlcsig(dataX,snr,lcParams)
% Generate a linear chirp signal
% S = GENLCSIG(X,SNR,P)
% Generates a linear chirp signal S. X is the vector of time stamps at
% which the samples of the signal are to be computed. SNR is the matched
% filtering signal-to-noise ratio of S and P is the vector of three
% parameters [f0, f1, phi0] of the signal:
% sin(2*pi*(f0*t + 0.5*f1*t^2) + phi0), where f0 is the starting frequency
% in Hz, f1 is the rate of increase of frequency in Hz/sec and phi0 is the
% initial phase in radians.

phaseVec = 2*pi*(lcParams(1)*dataX + 0.5*lcParams(2)*dataX.^2) + lcParams(3);
sigVec = sin(phaseVec);
sigVec = snr*sigVec/norm(sigVec);
end
