% Generate and plot a linear transient chirp for decreasing sampling intervals
% Generates a linear transient chirp signal
% s(t) = A*sin(2*pi*(f0*(t-ta) + f1*(t-ta)^2) + phi0) for ta <= t <= ta+L
% s(t) = 0 otherwise
% and plots it for several sampling intervals, from coarse to fine. Reduce
% the sampling interval until the plot stops changing significantly.
% The signal is generated by the local function GENLTCSIG at the end of
% this file. It then plots the periodogram of the most finely sampled signal.

% Daniel Rodriguez, September 2026

%% Signal parameters
snr = 10;               % Matched filtering SNR (sets the amplitude A)
startTime = 0.3;        % Start time ta of the chirp, in sec
startFreq = 5;          % Frequency f0 at the start of the chirp, in Hz
freqCoef = 20;          % Chirp coefficient f1 (frequency rises at 2*f1 Hz/sec)
initPhase = 0;          % Initial phase phi0 in radians
chirpLen = 0.4;         % Length L of the chirp, in sec
ltcParams = [startTime, startFreq, freqCoef, initPhase, chirpLen];
sigDuration = 1;        % Length of the whole data segment in seconds

%% Maximum instantaneous frequency
% Inside the chirp, f(t) = f0 + 2*f1*(t-ta) (no 1/2 in this formula), which
% is largest at the end of the chirp, t = ta + L
maxFreq = startFreq + 2*freqCoef*chirpLen;
disp(['Maximum instantaneous frequency = ', num2str(maxFreq), ' Hz']);

%% Sampling frequencies to try, as multiples of maxFreq
sampFreqList = [2, 5, 10, 50]*maxFreq;
nPlots = length(sampFreqList);

%% Generate and plot the signal for each sampling frequency
figure;
for k = 1:nPlots
    sampFreq = sampFreqList(k);                 % 1/Delta
    sampIntrvl = 1/sampFreq;                    % Delta
    nSamples = floor(sigDuration/sampIntrvl);   % N
    timeVec = (0:(nSamples-1))*sampIntrvl;      % t = n*Delta, n = 0,...,N-1

    sigVec = genltcsig(timeVec, snr, ltcParams);

    subplot(nPlots, 1, k);
    plot(timeVec, sigVec, '.-');
    xlabel('Time (sec)');
    ylabel('Transient chirp');
    title(['Sampling frequency = ', num2str(sampFreq), ' Hz (', ...
           num2str(sampFreq/maxFreq), ' x max. frequency)']);
end

%% Periodogram (magnitude of the FFT)
% Uses the signal from the last (finest) sampling frequency in the loop
kNyq = floor(nSamples/2) + 1;           % Index of the Nyquist frequency
freqSpacing = 1/(nSamples*sampIntrvl);  % Frequency spacing 1/(N*Delta)
posFreq = (0:(kNyq-1))*freqSpacing;     % Positive Fourier frequencies
fftSig = fft(sigVec);
fftSig = fftSig(1:kNyq);                % Keep positive frequencies only

figure;
plot(posFreq, abs(fftSig), '.-');
xlim([0, 2*maxFreq]);                   % Zoom in on where the signal is
xlabel('Frequency (Hz)');
ylabel('|FFT|');
title('Periodogram: linear transient chirp');

%% Local function
function sigVec = genltcsig(dataX,snr,ltcParams)
% Generate a linear transient chirp signal
% S = GENLTCSIG(X,SNR,P)
% Generates a linear transient chirp signal S. X is the vector of time
% stamps at which the samples of the signal are to be computed. SNR is the
% matched filtering signal-to-noise ratio of S and P is the vector of five
% parameters [ta, f0, f1, phi0, L] of the signal:
% sin(2*pi*(f0*(t-ta) + f1*(t-ta)^2) + phi0) for ta <= t <= ta+L and 0
% otherwise, where ta is the start time in sec, f0 is the starting
% frequency in Hz, f1 is the chirp coefficient in Hz/sec, phi0 is the
% initial phase in radians and L is the length of the chirp in sec.

sigVec = zeros(size(dataX));
inChirp = (dataX >= ltcParams(1)) & (dataX <= ltcParams(1) + ltcParams(5));
shiftedTime = dataX(inChirp) - ltcParams(1);   % t - ta
phaseVec = 2*pi*(ltcParams(2)*shiftedTime + ltcParams(3)*shiftedTime.^2) ...
           + ltcParams(4);
sigVec(inChirp) = sin(phaseVec);
sigVec = snr*sigVec/norm(sigVec);
end
