% Generate and plot a sinusoidal signal for decreasing sampling intervals
% Generates a sinusoidal signal s(t) = A*sin(2*pi*f0*t + phi0) and plots it
% for several sampling intervals, from coarse to fine. Reduce the sampling
% interval until the plot stops changing significantly.
% The signal is generated by the local function GENSINSIG at the end of
% this file. It then plots periodograms for f0 stepped in increments 
% smaller than 1/T.

% Daniel Rodriguez, September 2026

%% Signal parameters
snr = 10;               % Matched filtering SNR (sets the amplitude A)
sigFreq = 10;           % Frequency f0 in Hz
initPhase = pi/4;       % Initial phase phi0 in radians
sinParams = [sigFreq, initPhase];
sigDuration = 1;        % Length of the signal in seconds

%% Sampling frequencies to try, as multiples of the signal frequency
% The frequency of a sinusoid is constant, so f0 is also the maximum
maxFreq = sigFreq;
sampFreqList = [2, 5, 10, 50]*maxFreq;
nPlots = length(sampFreqList);

%% Generate and plot the signal for each sampling frequency
figure;
for k = 1:nPlots
    sampFreq = sampFreqList(k);                 % 1/Delta
    sampIntrvl = 1/sampFreq;                    % Delta
    nSamples = floor(sigDuration/sampIntrvl);   % N
    timeVec = (0:(nSamples-1))*sampIntrvl;      % t = n*Delta, n = 0,...,N-1

    sigVec = gensinsig(timeVec, snr, sinParams);

    subplot(nPlots, 1, k);
    plot(timeVec, sigVec, '.-');
    xlabel('Time (sec)');
    ylabel('Sinusoid');
    title(['Sampling frequency = ', num2str(sampFreq), ' Hz (', ...
           num2str(sampFreq/maxFreq), ' x signal frequency)']);
end

%% Periodogram (magnitude of the FFT) for small steps in frequency
% Uses the time stamps from the last (finest) sampling frequency in the loop
% and regenerates the signal with its frequency f0 stepped by less than 1/T
kNyq = floor(nSamples/2) + 1;           % Index of the Nyquist frequency
freqSpacing = 1/(nSamples*sampIntrvl);  % Frequency spacing 1/(N*Delta)
posFreq = (0:(kNyq-1))*freqSpacing;     % Positive Fourier frequencies

freqList = sigFreq + [0, 0.25, 0.5, 0.75, 1];  % Values of f0 to try, in Hz
nFreqs = length(freqList);

figure;
for k = 1:nFreqs
    sigVecK = gensinsig(timeVec, snr, [freqList(k), initPhase]);
    fftSig = fft(sigVecK);
    fftSig = fftSig(1:kNyq);            % Keep positive frequencies only

    subplot(nFreqs, 1, k);
    plot(posFreq, abs(fftSig), '.-');
    xlim([0, 2*maxFreq]);               % Same range on every subplot
    xlabel('Frequency (Hz)');
    ylabel('|FFT|');
    title(['Periodogram: sinusoid, f0 = ', num2str(freqList(k)), ' Hz']);
end

%% Zero-padded periodogram for the last frequency (f0 = sigFreq + 1)
% Padding with zeros adds frequency points between the Fourier frequencies,
% which traces out the underlying sinc function. It does not improve the
% frequency resolution, which is still set by the signal length T.
padFreq = freqList(end);                % 11 Hz with the default sigFreq
sigVecPad = gensinsig(timeVec, snr, [padFreq, initPhase]);
nPad = 16*nSamples;                     % Padded length (16x the samples)
kNyqPad = floor(nPad/2) + 1;            % Nyquist index for padded length
posFreqPad = (0:(kNyqPad-1))/(nPad*sampIntrvl);  % Spacing 1/(nPad*Delta)
fftSigPad = fft(sigVecPad, nPad);       % fft appends the zeros
fftSigPad = fftSigPad(1:kNyqPad);       % Keep positive frequencies only

fftSigNoPad = fft(sigVecPad);           % Unpadded FFT, for comparison
fftSigNoPad = fftSigNoPad(1:kNyq);

figure;
plot(posFreqPad, abs(fftSigPad));
hold on;
plot(posFreq, abs(fftSigNoPad), 'o');
hold off;
xlim([0, 2*maxFreq]);
xlabel('Frequency (Hz)');
ylabel('|FFT|');
legend('Zero-padded', 'Original Fourier frequencies');
title(['Zero-padded periodogram: sinusoid, f0 = ', num2str(padFreq), ' Hz']);

%% Local function
function sigVec = gensinsig(dataX,snr,sinParams)
% Generate a sinusoidal signal
% S = GENSINSIG(X,SNR,P)
% Generates a sinusoidal signal S. X is the vector of time stamps at which
% the samples of the signal are to be computed. SNR is the matched
% filtering signal-to-noise ratio of S and P is the vector of two
% parameters [f0, phi0] of the signal: sin(2*pi*f0*t + phi0), where f0 is
% the frequency in Hz and phi0 is the initial phase in radians.

phaseVec = 2*pi*sinParams(1)*dataX + sinParams(2);
sigVec = sin(phaseVec);
sigVec = snr*sigVec/norm(sigVec);
end
